# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: Build_stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        # npm install
        # npm run build --if-present
      displayName: 'npm install, build'

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*
          !node_modules/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: MyBuildOutputs
      

- stage: Deploy_stage
  jobs:
  - deployment: VMDeploy
    displayName: web
    pool:
      vmImage: 'Ubuntu-16.04'
    environment:
      name: Development
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Starting deployment script run" && sudo apt-get update && curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && sudo apt-get install -y nodejs && sudo ln -sf /usr/bin/nodejs /usr/bin/node && sudo npm install && sudo apt-get install -y nginx && sudo rm -f /etc/nginx/sites-enabled/default && sudo cp node-app-nginx-config /etc/nginx/sites-available/ && sudo ln -sf /etc/nginx/sites-available/node-app-nginx-config /etc/nginx/sites-enabled/node-app-nginx-config && sudo service nginx restart && sudo npm install -g pm2 && sudo pm2 start -f app.js && sudo pm2 startup systemd && sudo pm2 save && echo "End of script run"